sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin
    options:  { i18n: false }

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting
    options:  { i18n: false }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin
    options:  { i18n: false }

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin
    options:  { i18n: false }
