services:
  # Menus
  sonata.lopati.admin.categoria:
    class: LoPati\AdminBundle\Admin\CategoriaAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Menús', label: 'primer nivell' }
    arguments:
      - null
      - LoPati\MenuBundle\Entity\Categoria
      - AdminBundle:Admin
  sonata.lopati.admin.subcategoria:
    class: LoPati\AdminBundle\Admin\SubCategoriaAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Menús', label: 'segon nivell' }
    arguments:
      - null
      - LoPati\MenuBundle\Entity\SubCategoria
      - AdminBundle:Admin
  # Sliders
  sonata.lopati.admin.slider:
    class: LoPati\AdminBundle\Admin\SliderAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Slider', label: 'slide' }
    arguments:
      - null
      - LoPati\BlogBundle\Entity\SliderImage
      - AdminBundle:Admin
  # Pages
  sonata.lopati.admin.pagina:
    class: LoPati\AdminBundle\Admin\PaginaAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Pàgines', label: 'pàgina' }
    arguments:
      - null
      - LoPati\BlogBundle\Entity\Pagina
      - AdminBundle:PaginaAdmin
  sonata.lopati.admin.page_newsletter:
    class: LoPati\AdminBundle\Admin\NewsletterPaginaAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Pàgines', label: 'newsletter de pàgina' }
    arguments:
      - null
      - LoPati\NewsletterBundle\Entity\Newsletter
      - AdminBundle:NewsletterPageAdmin
  # Archives
  sonata.lopati.admin.arxiu:
    class: LoPati\AdminBundle\Admin\ArxiuAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Arxius', label: 'arxiu' }
    arguments:
      - null
      - LoPati\BlogBundle\Entity\Arxiu
      - AdminBundle:Admin 
  # Newsletters
  sonata.lopati.admin.newslettergroup:
    class: LoPati\AdminBundle\Admin\NewsletterGroupAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Newsletters', label: 'grup' }
    arguments:
      - null
      - LoPati\NewsletterBundle\Entity\NewsletterGroup
      - AdminBundle:Admin
  sonata.lopati.admin.newsletteruser:
    class: LoPati\AdminBundle\Admin\NewsletterUserAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Newsletters', label: 'usuari' }
    arguments:
      - null
      - LoPati\NewsletterBundle\Entity\NewsletterUser
      - AdminBundle:NewsletterUserAdmin
  sonata.lopati.admin.isolatednewsletter:
    class: LoPati\AdminBundle\Admin\IsolatedNewsletterAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Newsletters', label: 'newsletter' }
    arguments:
      - null
      - LoPati\NewsletterBundle\Entity\IsolatedNewsletter
      - AdminBundle:IsolatedNewsletterAdmin
  sonata.lopati.admin.isolatednewsletterpost:
    class: LoPati\AdminBundle\Admin\IsolatedNewsletterPostAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Newsletters', label: 'newsletter-post', show_in_dashboard: false }
    arguments:
      - null
      - LoPati\NewsletterBundle\Entity\IsolatedNewsletterPost
      - AdminBundle:IsolatedNewsletterPostAdmin
  # Artist
  sonata.lopati.admin.artista:
    class: LoPati\AdminBundle\Admin\ArtistaAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Irradiador', label: 'artista' }
    arguments:
      - null
      - LoPati\ArtistaBundle\Entity\Artista
      - AdminBundle:Admin
  # Configs
  sonata.lopati.admin.configuracio:
    class: LoPati\AdminBundle\Admin\ConfiguracioAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Configuracions', label: 'peu de pàgina' }
    arguments:
      - null
      - LoPati\BlogBundle\Entity\Configuracio
      - AdminBundle:Admin
  sonata.lopati.admin.configuracio.dies.laborals.agenda:
    class: LoPati\AdminBundle\Admin\ConfiguracioDiesLaboralsAgendaAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'Configuracions', label: 'dies laborals agenda' }
    arguments:
      - null
      - LoPati\BlogBundle\Entity\ConfiguracioDiesLaboralsAgenda
      - AdminBundle:Admin
  # Form types
  app.form_type_action_button:
    class: LoPati\AdminBundle\Form\Type\EditIsolatedNewsletterPostActionButtonFormType
    tags:
      - { name: form.type, alias: action_button }
  # Mailer
  app.mailer.service:
    class: LoPati\AdminBundle\Service\MailerService
    arguments:
      - "@sendgrid"
      - "@logger"
      - "%sendgrip_api_key%"
  app.newsletter_user_manager.service:
    class: LoPati\AdminBundle\Service\NewsletterUserManagementService
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@validator"
# Sonata Blocks
  sonata.admin.block.isolated_newsletter_xls_import:
    class: LoPati\AdminBundle\Admin\Block\IsolatedNewsletterXlsImportBlock
    tags:
      - { name: sonata.block }
    arguments:
      - "sonata.admin.block.messages"
      - "@templating"
      - "@form.factory"
      - "@router"
  # Twig
  app.twig_extension:
    class: LoPati\AdminBundle\Twig\AdminExtensionTwig
    public: false
    tags:
      - { name: twig.extension }
