calendari:
    path:     /{_locale}/calendari/{fletxa}/
    defaults: { _controller: AgendaBundle:Default:calendari }
    requirements:
        fletxa: dreta|esquerra
        _locale: ca|es

agenda_ca:
    path:     /{_locale}/agenda/{year}/{month}/{day}/
    defaults: { _controller: AgendaBundle:Default:agenda }
    requirements:
        _locale: ca

agenda_es:
    path:     /{_locale}/agenda/{year}/{month}/{day}/
    defaults: { _controller: AgendaBundle:Default:agenda }
    requirements:
        _locale: es
