newsletter_user:
    pattern:  /newsletter/suscribe
    defaults: { _controller: NewsletterBundle:Default:suscribe}
    requirements:
      _method:  POST
      
newsletter_unsuscribe:
    pattern:  /newsletter/unsuscribe/{token}
    defaults: { _controller: NewsletterBundle:Default:unsuscribe}

newsletter_confirm_unsuscribe:
    pattern:  /newsletter/confirm/unsuscribe/
    defaults: { _controller: NewsletterBundle:Default:confirmUnsuscribe}

newsletter_unsuscribe:
    pattern:  /newsletter/unsuscribe/{token}
    defaults: { _controller: NewsletterBundle:Default:unsuscribe}

newsletter_confirmation:
    pattern:  /newsletter/confirmation/{token}
    defaults: { _controller: NewsletterBundle:Default:confirmation}

newsletter:
    pattern: /{_locale}/newsletter/{data}/
    defaults: { _controller: NewsletterBundle:Default:visit }
    requirements:
       _locale: ca|es|en
