Frontend:
    resource: "@NewsletterBundle/Controller"
    type:     annotation
    prefix:   /

newsletter_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: NewsletterBundle:Default:index }

newsletter_user:
    pattern:  /newsletter/suscribe
    defaults: { _controller: NewsletterBundle:Default:suscribe}
    requirements:
      _method:  POST

newsletter_unsuscribe:
    pattern:  /newsletter/unsuscribe/{token}
    defaults: { _controller: NewsletterBundle:Default:unsuscribe}

newsletter_confirmation:
    pattern:  /newsletter/confirmation/{token}
    defaults: { _controller: NewsletterBundle:Default:confirmation}

newsletter:
    pattern: /{_locale}/newsletter/{data}/
    defaults: { _controller: NewsletterBundle:Default:visit }
    requirements:
       _locale: ca|es|en