newsletter_user:
    path:  /newsletter/suscribe
    defaults: { _controller: NewsletterBundle:Default:suscribe }
    requirements:
      method:  POST

newsletter_confirmation:
    path:  /newsletter/confirmation/{token}
    defaults: { _controller: NewsletterBundle:Default:confirmation }

newsletter_unsuscribe:
    path:  /newsletter/unsuscribe/{token}
    defaults: { _controller: NewsletterBundle:Default:unsuscribe }

newsletter_confirm_unsuscribe:
    path:  /newsletter/confirm/unsuscribe/
    defaults: { _controller: NewsletterBundle:Default:confirmUnsuscribe }

newsletter:
    path: /{_locale}/newsletter/{data}/
    defaults: { _controller: NewsletterBundle:Default:visit }
    requirements:
       _locale: ca|es

isolated_newsletter_preview:
    path: /newsletter/{id}/
    defaults: { _controller: NewsletterBundle:Default:isolatedPreview }

admin_lopati_newsletter_newsletteruser_async_search:
    path: /admin/newsletter/user/async/search-users-by-email/
    defaults: { _controller: NewsletterBundle:NewsletterUser:searchUsersByEmailAsync }

admin_lopati_newsletter_newsletteruser_async_get:
    path: /admin/newsletter/user/async/get-users/
    defaults: { _controller: NewsletterBundle:NewsletterUser:getUsersAsync }
