services:
    newsletter.build_content:
        class: LoPati\NewsletterBundle\Manager\NewsletterManager
        arguments:
            - "@templating"
            - "@translator"
            - "@hip_mandrill.dispatcher"
            - "@hip_mandrill.client"
            - "@tystr_sendgrid.sendgrid"
