services:
    newsletter.build_content:
        class: LoPati\NewsletterBundle\Manager\NewsletterManager
        tags:
            - { name: monolog.logger, channel: sendgrid }
        arguments:
            - "@templating"
            - "@translator"
    newsletter.sendgrid.hooks:
        class: LoPati\NewsletterBundle\Listener\SendgridListener
        tags:
            - { name: monolog.logger, channel: sendgrid }
            - { name: kernel.event_listener, event: sendgrid.processed, method: onEmailProcessed }
            - { name: kernel.event_listener, event: sendgrid.dropped, method: onEmailDropped }
            - { name: kernel.event_listener, event: sendgrid.delivered, method: onEmailDelivered }
            - { name: kernel.event_listener, event: sendgrid.bounce, method: onEmailBounce }
            - { name: kernel.event_listener, event: sendgrid.spamreport, method: onEmailSpam }
            - { name: kernel.event_listener, event: sendgrid.unsubscribe, method: onEmailUnsubscribe }
        arguments:
            - "@logger"
