parameters:
#    newsletter.example.class: LoPati\NewsletterBundle\Example

services:
    newsletter.build_content:
        class: LoPati\NewsletterBundle\Manager\NewsletterManager
        arguments: [ @templating, @translator ]
