services:
    newsletter.build_content:
        class: LoPati\NewsletterBundle\Manager\NewsletterManager
        arguments:
            - "@templating"
            - "@translator"
            - "%sendgrip_api_key%"
