language: php

php:
  - 5.5
  - 5.6
#  - 7.0

before_script:
  - mysql -e 'create database IF NOT EXISTS symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer selfupdate
  - composer install
  - php app/console doctrine:databa:create --no-interaction --env=test
  - php app/console doctrine:schema:create --no-interaction --env=test
  - php app/console hautelook_alice:doctrine:fixtures:load --no-interaction --env=test

script:
  - phpunit -c app

notifications:
  email:
    -  david@flux.cat

branches:
  only:
    - master
    - devel
