imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

swiftmailer:
    transport: gmail
    username: metalrockero@gmail.com
    password: c0b1n1na
    delivery_address: metalrockero@gmail.com
    spool:
      type: file
      path: %kernel.cache_dir%/swiftmailer/spool
    antiflood:
        threshold:            99
        sleep:                0
    
web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
