imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata.yml }

# Symfony
framework:
    translator:      { fallbacks: [ "%locale%" ] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: [ "twig" ]
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
        - "MenuBundle:Default:form.html.twig"
    globals:
        main_brand_title:  "Lo Pati"
        admin_tag_version: "2.0.4"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Doctrine
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/AppBundle/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale:       "%locale%"
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   false
            sortable:       false
            tree:           false

# A2lix
a2lix_translation_form:
    locales: [ en, es ]
    default_required: true
    manager_registry: doctrine
    templating:       "::A2lix/default.html.twig"

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     LoPati\UserBundle\Entity\User
    group:
        group_class:   LoPati\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# TinyMCE
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: "%locale%"
    theme:
        simple:
            mode: "textareas"
            theme: "advanced"
            theme_advanced_buttons1: "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink,forecolor,backcolor"
            theme_advanced_buttons2: "outdent,indent,code,|,pastetext"
            theme_advanced_buttons3:
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            plugins: "paste link"
            paste_auto_cleanup_on_paste : true
            paste_remove_styles: true
            paste_remove_styles_if_webkit: true
            paste_strip_class_attributes: true
            paste_retain_style_properties: "strong,p,color"
            theme_advanced_buttons1_add: "fullscreen"

# Vich
vich_uploader:
    db_driver: orm
    mappings:
        imatge:
            uri_prefix:         /uploads/images
            upload_destination: %kernel.root_dir%/../web/uploads/images
            namer:              vich_uploader.namer_uniqid
        pdf:
            uri_prefix:         /uploads/documents
            upload_destination: %kernel.root_dir%/../web/uploads/documents
            namer:              vich_uploader.namer_origname
        artista:
            uri_prefix:         /uploads/artists
            upload_destination: %kernel.root_dir%/../web/uploads/artists
            namer:              vich_uploader.namer_uniqid
        artistapdf:
            uri_prefix:         /uploads/artists/cv
            upload_destination: %kernel.root_dir%/../web/uploads/artists/cv
            namer:              vich_uploader.namer_origname
        slider:
            uri_prefix:         /uploads/slides
            upload_destination: %kernel.root_dir%/../web/uploads/slides
            namer:              vich_uploader.namer_uniqid

# Liip Imagine
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        imatge_pagina:
            quality: 90
            filters:
                thumbnail: { size: [710, null], mode: outbound }
        imatge_pagina_irradiador:
            quality: 90
            filters:
                thumbnail: { size: [460, null], mode: outbound }
        portada:
            quality: 90
            filters:
                thumbnail: { size: [174, 174], mode: outbound }
        thumb_imatge_pagina:
            quality: 70
            filters:
                thumbnail: { size: [155, null], mode: outbound }
        thumb_imatge_pagina_arbre_continguts:
            quality: 70
            filters:
                thumbnail: { size: [50, null], mode: outbound }
        thumb_imatge_admin_list_view:
            quality: 70
            filters:
                thumbnail: { size: [100, null], mode: outbound }
        imatge_pagina_newsletter:
            quality: 80
            filters:
                thumbnail: { size: [578, null], mode: outbound }
        imatge460x300:
            quality: 90
            filters:
                thumbnail: { size: [460, 300], mode: outbound }
        480xY:
            quality: 90
            filters:
                thumbnail: { size: [480, null], mode: outbound }
        imatge756x400:
            quality: 85
            filters:
                thumbnail: { size: [756, 400], mode: outbound, allow_upscale: true }

# FOS Elasticsearch
# Move to config_prod.yml if it's necessary to avoid Elasticasearch on devel environments
fos_elastica:
    clients:
        default: { host: localhost, port: %port_elastica% }
    indexes:
        website:
            client: default
            types:
                pagines:
                    mappings:
                        titol: { boost: 5 }
                        descripcio: { boost: 3 }
                        translatedTitleEs: { boost: 5 }
                        translatedDescripcioEs: { boost: 3 }
                        translatedTitleEn: { boost: 5 }
                        translatedDescripcioEn: { boost: 3 }
                    persistence:
                        driver: orm
                        model: LoPati\BlogBundle\Entity\Pagina
                        provider:
                        listener:
                        finder:

# Genemu
genemu_form:
    select2: ~
    date:    ~

# Mandril
hip_mandrill:
    api_key: "%mandril_api_key%"
    default:
        sender:       "butlleti@lopati.cat"
        sender_name:  "Lo Pati"
