imports:
    - { resource: parameters.yml }
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

swiftmailer:
    transport: %mailer_transport%
    username: %mailer_user%
    password:   %mailer_password%
    delivery_address:   %swiftmailer_delivery_address_dev_environment%
    host:       %mailer_host%
    encryption: %encryption%
    auth_mode:  %auth_mode%

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

fos_elastica:
    clients:
        default: { host: localhost, port: %port_elastica% }
    indexes:
        website:
            client: default
            types:
                pagines:
                    mappings:
                        titol: { boost: 5 }
                        descripcio: { boost: 3 }
                        translatedTitleEs: { boost: 5 }
                        translatedDescripcioEs: { boost: 3 }
                        translatedTitleEn: { boost: 5 }
                        translatedDescripcioEn: { boost: 3 }
                    persistence:
                        driver: orm
                        model: LoPati\BlogBundle\Entity\Pagina
                        provider:
                        listener:
                        finder:
