imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: media.yml }
    - { resource: sonata.yml }

# Symfony
framework:
    translator:      { fallbacks: [ "%locale%" ] }
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    secret:          "%secret%"
    fragments:       ~
    trusted_hosts:   ~
    trusted_proxies: ~
    form:            ~
    csrf_protection: ~
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: [ "twig" ]
    session:
        handler_id:  ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
        - "MenuBundle:Default:form.html.twig"
        - "AdminBundle:Form:action_button_from_template.html.twig"
    globals:
        main_brand_title:        "Lo Pati"
        admin_tag_version:       "2.4.1"
        id_page_item_irradiador: "%id_page_item_irradiador%"

# Swiftmailer
swiftmailer:
    transport:  "%mailer_transport%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    host:       "%mailer_host%"
    encryption: "%encryption%"
    auth_mode:  "%auth_mode%"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AdminBundle, AgendaBundle, ArtistaBundle, BlogBundle, MenuBundle, NewsletterBundle, UserBundle ]
    filters:
        cssrewrite: ~

# Doctrine
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping:                true

# Doctrine Migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/AppBundle/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale:       "%locale%"
    translation_fallback: true
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   true
            sortable:       false
            tree:           false

# Monolog
monolog:
    handlers:
        sendgrid:
            type:     stream
            level:    info
            path:     "%kernel.logs_dir%/sendgrid.log"
            channels: [ sendgrid ]

# A2lix
a2lix_translation_form:
    locales: [ en, es ]
    default_required: true
    manager_registry: doctrine
    templating:       "::A2lix/default.html.twig"

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     LoPati\UserBundle\Entity\User
    group:
        group_class:   LoPati\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# TinyMCE
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    language: "%locale%"
    theme:
        simple:
            mode: "textareas"
            theme: "advanced"
            theme_advanced_buttons1: "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink,forecolor,backcolor"
            theme_advanced_buttons2: "outdent,indent,code,|,pastetext"
            theme_advanced_buttons3:
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            plugins: "paste link"
            paste_auto_cleanup_on_paste : true
            paste_remove_styles: true
            paste_remove_styles_if_webkit: true
            paste_strip_class_attributes: true
            paste_retain_style_properties: "strong,p,color"
            theme_advanced_buttons1_add: "fullscreen"

# FOS Elasticsearch
# Move to config_prod.yml if it's necessary to avoid Elasticasearch on devel environments
fos_elastica:
    clients:
        default: { host: localhost, port: "%port_elastica%" }
    indexes:
        website:
            client: default
            types:
                pagines:
                    mappings:
                        titol: { boost: 5 }
                        descripcio: { boost: 3 }
                        translatedTitleEs: { boost: 5 }
                        translatedDescripcioEs: { boost: 3 }
                        translatedTitleEn: { boost: 5 }
                        translatedDescripcioEn: { boost: 3 }
                    persistence:
                        driver: orm
                        model: LoPati\BlogBundle\Entity\Pagina
                        provider:
                        listener:
                        finder:

# Genemu
genemu_form:
    select2: ~
    date:    ~

# Tystr Sendgrid
tystr_sendgrid:
    username: "%sendgrip_username%"
    password: "%sendgrip_password%"
