imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
swiftmailer:
    transport: %mailer_transport%
    username: %mailer_user%
    password:   %mailer_password%
    host:       %mailer_host%
    encryption: %encryption%
    auth_mode:  %auth_mode%

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

foq_elastica:
    clients:
        default: { host: localhost, port: %port_elastica% }

    indexes:
        website:
            client: default
            types:
                pagines:
                    mappings:
                        titol: { boost: 5 }
                        descripcio: { boost: 3 }
                        translatedTitleEs: { boost: 5 }
                        translatedDescripcioEs: { boost: 3 }
                        translatedTitleEn: { boost: 5 }
                        translatedDescripcioEn: { boost: 3 }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model: LoPati\BlogBundle\Entity\Pagina
                        provider:
                        listener:
                        finder: