imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: media.yml }
    - { resource: sonata.yml }

# Symfony
framework:
    translator:      { fallbacks: [ "%locale%" ] }
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    secret:          "%secret%"
    fragments:       ~
    trusted_hosts:   ~
    trusted_proxies: ~
    form:            ~
    csrf_protection: ~
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: [ "twig" ]
    session:
        name:       LPSESSID
        handler_id: ~
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "SonataCoreBundle:Form:datepicker.html.twig"
        - "MenuBundle:Default:form.html.twig"
        - "AdminBundle:Form:action_button_from_template.html.twig"
    globals:
        main_brand_title:        "Lo Pati"
        admin_tag_version:       "v2.6.4"
        id_page_item_irradiador: "%id_page_item_irradiador%"
        addthis_api_key:         "%addthis_api_key%"

# Swiftmailer
swiftmailer:
    transport:  "%mailer_transport%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    host:       "%mailer_host%"
    encryption: "%encryption%"
    auth_mode:  "%auth_mode%"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AdminBundle, AgendaBundle, ArtistaBundle, BlogBundle, MenuBundle, NewsletterBundle, UserBundle ]
    filters:
        cssrewrite: ~

# Doctrine
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping:                true

# Doctrine Migrations
doctrine_migrations:
    dir_name:  "%kernel.root_dir%/../src/AppBundle/DoctrineMigrations"
    namespace: AppBundle\DoctrineMigrations

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale:       "%locale%"
    translation_fallback: true
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   true
            sortable:       false
            tree:           false

# Monolog
monolog:
    handlers:
        sendgrid:
            type:     stream
            level:    info
            path:     "%kernel.logs_dir%/sendgrid.log"
            channels: [ sendgrid ]

# A2lix
a2lix_translation_form:
    locales:          [ en, es ]
    default_required: true
    manager_registry: doctrine
    templating:       "::A2lix/default.html.twig"

# FOS User
fos_user:
    db_driver:     orm
    firewall_name: admin
    user_class:    LoPati\UserBundle\Entity\User
    group:
        group_class:   LoPati\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager
    from_email:
        address:     "%sendgrid_from_email%"
        sender_name: "%sendgrid_from_name%"

# TinyMCE
stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector:       ".tinymce"
    base_url:       "https://www.lopati.cat/"
    language:       "%locale%"
    theme:
        simple:
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            image_advtab: true

# FOS Elasticsearch
# Move to config_prod.yml if it's necessary to avoid Elasticasearch on devel environments
fos_elastica:
    clients:
        default: { host: localhost, port: "%port_elastica%" }
    indexes:
        lopati_website:
            client: default
            types:
                pagines:
                    mappings:
                        titol: { boost: 5 }
                        descripcio: { boost: 3 }
                        translatedTitleEs: { boost: 5 }
                        translatedDescripcioEs: { boost: 3 }
                        translatedTitleEn: { boost: 5 }
                        translatedDescripcioEn: { boost: 3 }
                    persistence:
                        driver: orm
                        model: LoPati\BlogBundle\Entity\Pagina
                        provider:
                        listener:
                        finder:

# Genemu
genemu_form:
    select2: ~
    date:    ~

# Tystr Sendgrid
tystr_sendgrid:
    username: "%sendgrip_username%"
    password: "%sendgrip_password%"
