AgendaBundle:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

BlogBundle:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

MenuBundle:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

ArtistaBundle:
    resource: "@ArtistaBundle/Resources/config/routing.yml"
    prefix:   /

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /

AdminBundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'
    options:  { i18n: false }
