agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /

    
BlogBundle:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /
    
MenuBundle:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine
    

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
