BlogBundle:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /
    
MenuBundle:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine
    
LexikMailerBundle:
    resource: "@LexikMailerBundle/Resources/config/routing.xml"
    prefix:   /news

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
