# Don't move routing priorities
AgendaBundle:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

BlogBundle:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

MenuBundle:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

ArtistaBundle:
    resource: "@ArtistaBundle/Resources/config/routing.yml"
    prefix:   /

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /

AdminBundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

sendgrid_hooks:
    resource: "@TystrSendgridBundle/Resources/config/routing.xml"

_imagine:
    resource: .
    type:     imagine
