artista:
    resource: "@ArtistaBundle/Resources/config/routing.yml"
    prefix:   /

agenda:
    resource: "@AgendaBundle/Resources/config/routing.yml"
    prefix:   /

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /

    
BlogBundle:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /
    
MenuBundle:
    resource: "@MenuBundle/Resources/config/routing.yml"
    prefix:   /

_imagine:
    resource: .
    type:     imagine
