#!/bin/bash

if [ -x "$(command -v php-cs-fixer)" ]; then
    FILES=`git diff --name-only`
    printf '%s\n' "$FILES" | while IFS= read -r FILE
    do
        if [[ $FILE == "src/"* ]]; then
            php-cs-fixer fix "$FILE" --rules=@Symfony
            # git add "$FILE"
        fi
    done
    FILES=`git diff --name-only --staged`
    printf '%s\n' "$FILES" | while IFS= read -r FILE
    do
        if [[ $FILE == "src/"* ]]; then
            php-cs-fixer fix "$FILE" --rules=@Symfony
            git add "$FILE"
        fi
    done
else
    echo "Unable to find php-cs-fixer command. Please, check https://github.com/FriendsOfPHP/PHP-CS-Fixer to install it globally (manual) in your system."
fi
