inici:
  path: /
  defaults: { _controller: BlogBundle:Default:index}

portada:
  path: /{_locale}/
  defaults: { _controller: BlogBundle:Default:portada}
  requirements:
        _locale: ca|es|en

categoriaenenllas:
  path: /{_locale}/{categoria}/{id}/
  defaults: { _controller: BlogBundle:Default:pagina}
  requirements:
    id:  \d+
    method:  GET
    _locale: ca|es|en

arxiuarticle:
  path: /{_locale}/{arxiu}/{any}/{titol}/{id}/
  defaults: { _controller: BlogBundle:Default:arxiuArticle}
  requirements:
    _locale: ca|es|en
    id:  \d+
    any: \d+
    method:  GET

llista:
  path: /{_locale}/{categoria}/{subcategoria}/{categoria_id}/{subcategoria_id}/
  defaults: { _controller: BlogBundle:Default:llista}
  requirements:
    categoria_id: \d+
    subcategoria_id: \d+
    method:  GET
    _locale: ca|es|en

arxiullistaany:
  path: /{_locale}/{arxiu}/{any}/{categoria_id}/
  defaults: { _controller: BlogBundle:Default:arxiuLlistaAny}
  requirements:
    _locale: ca|es|en
    any:  \d+
    categoria_id: \d+
    method:  GET

arxiu:
  path: /{_locale}/{arxiu}/{categoria}/{categoria_id}/
  defaults: { _controller: BlogBundle:Default:arxiu}
  requirements:
        _locale: ca|es|en
        arxiu: \d+
        categoria: "[a-zA-Z]+"
        categoria_id: \d+
        id: \d+

categoriasenseenllas:
  path: /{_locale}/{categoria}/{subcategoria}/{id}/
  defaults: { _controller: BlogBundle:Default:pagina}
  requirements:
    id:  \d+
    method:  GET

pagina:
  path: /{_locale}/{categoria}/{subcategoria}/{titol}/{id}/
  defaults: { _controller: BlogBundle:Default:article}
  requirements:
    id:  \d+
    method:  GET
    _locale: ca|es|en

search:
  path: /{_locale}/search/
  defaults: { _controller: BlogBundle:Default:search}
  requirements:
        _locale: ca|es|en

privacypolicy:
  path: /{_locale}/privacy-policy/
  defaults: { _controller: BlogBundle:Default:privacyPolicy}
  requirements:
        _locale: ca|es|en
