irradiador_ca:
    path:           /{_locale}/projectes/irradiador/
    defaults:       { _controller: ArtistaBundle:Default:index }
    requirements:
        _locale: ca

irradiador_es:
    path:           /{_locale}/proyectos/irradiador/
    defaults:       { _controller: ArtistaBundle:Default:index }
    requirements:
        _locale: es

irradiador_detail_ca:
    path:           /{_locale}/projectes/irradiador/{artista}/
    defaults:       { _controller: ArtistaBundle:Default:detail }
    requirements:
        _locale: ca

irradiador_detail_es:
    path:           /{_locale}/proyectos/irradiador/{artista}/
    defaults:       { _controller: ArtistaBundle:Default:detail }
    requirements:
        _locale: es
