irradiador_ca:
    pattern:        /{_locale}/projectes/irradiador/
    defaults:       { _controller: ArtistaBundle:Default:index }
    requirements:
        _locale: ca

irradiador_es:
    pattern:        /{_locale}/proyectos/irradiador/
    defaults:       { _controller: ArtistaBundle:Default:index }
    requirements:
        _locale: es

irradiador_en:
    pattern:        /{_locale}/projects/irradiador/
    defaults:       { _controller: ArtistaBundle:Default:index }
    requirements:
        _locale: en

irradiador_detail_ca:
    pattern:        /{_locale}/projectes/irradiador/{artista}/{id}
    defaults:       { _controller: ArtistaBundle:Default:detail }
    requirements:
        _locale: ca
        id: \d+

irradiador_detail_es:
    pattern:        /{_locale}/proyectos/irradiador/{artista}/{id}
    defaults:       { _controller: ArtistaBundle:Default:detail }
    requirements:
        _locale: es
        id: \d+

irradiador_detail_en:
    pattern:        /{_locale}/projects/irradiador/{artista}/{id}
    defaults:       { _controller: ArtistaBundle:Default:detail }
    requirements:
        _locale: en
        id: \d+
