parameters:
#    artista.example.class: LoPati\ArtistaBundle\Example

services:
#    artista.example:
#        class: %artista.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
